name: py3-intobj
channels:
- intel
- pytorch
- conda-forge
- defaults
dependencies:
- absl-py=1.0.0
- aiohttp=3.7.0
- async-timeout=3.0.1
- attrs=21.4.0
- blinker=1.4
- brotlipy=0.7.0
- c-ares=1.17.1
- cachetools=4.2.4
- chardet=3.0.4
- charset-normalizer=2.0.10
- click=8.0.3
- cryptography=35.0.0
- dataclasses=0.8
- google-auth=2.3.3
- google-auth-oauthlib=0.4.6
- grpcio=1.33.2
- idna=3.1
- importlib-metadata=4.10.0
- libprotobuf=3.13.0.1
- markdown=3.3.6
- multidict=4.7.5
- oauthlib=3.1.1
- protobuf=3.13.0.1
- pyasn1=0.4.8
- pyasn1-modules=0.2.7
- pycparser=2.21
- pyjwt=2.3.0
- pyopenssl=21.0.0
- pysocks=1.7.1
- python_abi=3.8
- pyu2f=0.1.5
- requests=2.27.1
- requests-oauthlib=1.3.0
- rsa=4.8
- tensorboard=2.7.0
- tensorboard-plugin-wit=1.8.1
- urllib3=1.26.8
- werkzeug=2.0.1
- yarl=1.6.3
- zipp=3.7.0
- _libgcc_mutex=0.1
- blas=1.0
- ca-certificates=2021.1.19
- certifi=2020.12.5
- cffi=1.14.6
- cudatoolkit=11.0.221
- intel-openmp=2020.2
- ld_impl_linux-64=2.33.1
- libedit=3.1.20191231
- libffi=3.3
- libgcc-ng=9.1.0
- libstdcxx-ng=9.1.0
- libuv=1.40.0
- mkl-include=2020.2
- mkl-service=2.3.0
- mkl_fft=1.3.0
- mkl_random=1.1.1
- ncurses=6.2
- ninja=1.10.2
- numpy=1.19.2
- numpy-base=1.19.2
- openssl=1.1.1m
- pip=21.0.1
- python=3.8.8
- readline=8.1
- setuptools=52.0.0
- six=1.15.0
- sqlite=3.33.0
- tensorboard-data-server=0.6.0
- tk=8.6.10
- typing_extensions=3.7.4.3
- wheel=0.36.2
- xz=5.2.5
- zlib=1.2.11
- mkl=2020.4
- tbb=2020.3
- pytorch=1.7.1=py3.8_cuda11.0.221_cudnn8.0.5_0

